# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Document Code

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  document:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
    - uses: actions/checkout@v1
    - run: npm i
    - run: npm run doc
